# Removes deprecated  --redirect-http-to=
- op: remove
  path: /spec/template/spec/containers/0/args/2
- op: remove
  path: /spec/template/spec/containers/0/livenessProbe
- op: remove
  path: /spec/template/spec/containers/0/readinessProbe
# sets resources
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

# resets KUBECONFIG entry to simple value
- op: replace
  path: /spec/template/spec/containers/0/env/0
  value:
    name: KUBECONFIG
    value: "/etc/kubeconfig/config"

# removes AWS env vars
- op: remove
  path: /spec/template/spec/containers/0/env/3
- op: remove
  path: /spec/template/spec/containers/0/env/2
- op: remove
  path: /spec/template/spec/containers/0/env/1

# removes aws-iam-token mount
- op: remove
  path: /spec/template/spec/containers/0/volumeMounts/12
- op: remove
  path: /spec/template/spec/volumes/12

# removes mount and volume for kubeconfig-k8s-infra-kops-prow-build
- op: remove
  path: /spec/template/spec/containers/0/volumeMounts/7
- op: remove
  path: /spec/template/spec/volumes/8

# removes mount and volume for kubeconfig-eks-prow-build-cluster
- op: remove
  path: /spec/template/spec/containers/0/volumeMounts/6
- op: remove
  path: /spec/template/spec/volumes/7
