apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: dhiller@redhat.com
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ellorent@redhat.com
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: bcarey@redhat.com
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ibezukh@redhat.com
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: dedicated-admins
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: 'system:serviceaccounts:dedicated-admin'
