apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: statusreconciler
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: statusreconciler
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-pods
  name: statusreconciler
rules:
- apiGroups:
  - "prow.k8s.io"
  resources:
  - prowjobs
  verbs:
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: statusreconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: statusreconciler
subjects:
- kind: ServiceAccount
  name: statusreconciler
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-pods
  name: statusreconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: statusreconciler
subjects:
- kind: ServiceAccount
  name: statusreconciler
  namespace: default
