---
apiVersion: v1
kind: Service
metadata:
  name: referee
  labels:
    app: referee
spec:
  ports:
  - name: default
    port: 9900
    protocol: TCP
    targetPort: 9900
  selector:
    app: referee
  type: ClusterIP
