---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: sriov
value: 1000000
preemptionPolicy: Never
globalDefault: false
description: "Allows sriov jobs to be scheduled with higher priority."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: vgpu
value: 1000000
preemptionPolicy: Never
globalDefault: false
description: "Allows gpu jobs to be scheduled with higher priority."
